spring.application.name=catalogo_mongo
server.port=8080

#MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/catalogo_libros

# Configuración de Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
